---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.10"

inputs:
  - name: source-code-deps
  - name: docker

run:
  path: ./ci/scripts/integration-tests.sh
  dir: source-code-deps
