---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.10"

inputs:
  - name: source-code-deps

run:
  path: ./ci/scripts/unit-tests.sh
  dir: source-code-deps
