environment: live
tag: latest
tribe: special
squad: wine
deployments:
  consumers:
    replicaCount: 4
    containerPort: 80
    repository: quay.io/hellofresh/wine-order-service
    pullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - "wine-order-service"
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
        - "wine-order-service"
        - "ready"
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    resources:
      requests:
        cpu: 250m
        memory: 100Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}
    hpa:
      #
      # To enable HPA, use values according to below example
      enabled: true
      replicas:
        min: 4
        max: 6
      metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 80

services:
  consumers:
    enabled: true
configMap:
  INTFOOD_DSN: "bar"
