# Environment tag
environment: ahoy
tag: latest
tribe: special
squad: wine
deployments:
  consumers:
    replicaCount: 1
    containerPort: 80
    repository: quay.io/hellofresh/wine-order-service
    pullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - "wine-order-service"
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
        - "wine-order-service"
        - "ready"
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    hpa:
      enabled: false
services:
  consumers:
    enabled: true
configMap:
  INTFOOD_DSN: "bar"
